#!/bin/sh
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
[ -f $sysresources ] && xrdb -merge $sysresources
[ -f $sysmodmap ] && xmodmap $sysmodmap
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

xbindkeys

WALLPAPER="$HOME/.config/wallpaper.jpg"
[ -f "$WALLPAPER" ] && hsetroot -solid "#111" -cover "$WALLPAPER"

fcitx5 -d
picom -b
dwmblocks &

# allow for quick reloading of dwm when sigkill
while :; do
  ssh-agent dwm
done
